name: Check Tweet

on:
  schedule:
    - cron: '16 12 * * 6'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy
        pip install python-dotenv
    - name: run
      run: |
        python sarazar_main.py
      env: 
        API_KEY: ${{secrets.API_KEY}}
        API_SECRET: ${{secrets.API_SECRET}}
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        ACCESS_SECRET: ${{secrets.ACCESS_SECRET}}
        
